"""create indexes

Revision ID: 7302554a408a
Revises: 3f0e6d79119c
Create Date: 2024-04-12 06:20:25.868432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7302554a408a'
down_revision: Union[str, None] = '3f0e6d79119c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_energy_stats_surplus'), 'energy_stats', ['surplus'], unique=False)
    op.create_index(op.f('ix_energy_stats_use_date'), 'energy_stats', ['use_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_stats_use_date'), table_name='energy_stats')
    op.drop_index(op.f('ix_energy_stats_surplus'), table_name='energy_stats')
    # ### end Alembic commands ###
